### PR TITLE
Added config syncing, barrel rotation, and removed old code

### PR DESCRIPTION
**Pull request by ekulxam**

### CODE REVIEW

**Comment by CammiePone** [comment]
im not currently at my pc and looking at the code is very Not Fun™ on mobile. can you explain or show a video of the barrel yaw/pitch stuff? kinda confused what that's about is all

**Comment by CammiePone** [comment]
also, the config syncing seems a little redundant. all the config stuff is server-side so it doesnt seem very important to sync it, especially not every so often since servers cant really reload their configs most of the time

if syncing does need to be done, i'd just do it on world join myself

**Comment by ekulxam** [comment]
Basically, if you're sneaking, the barrel will change its pitch or yaw depending on where you're looking at (so it isn't facing the same way every time). If you've been standing still for long enough, it will stop rotating.

I did the config syncing for the barrel rotation because that seems to be mostly client.

**Comment by CammiePone** [comment]
ahhh i see. well, i would only sync those two then, because the other config values are server-only and it would be better networking-wise to not sync them

**Comment by ekulxam** [comment]
Done

**Comment by CammiePone** [comment]
awesome animal

**Pull request merged**
