### PR TITLE
Port to 1.20.1

### PR DESCRIPTION
**Pull request by ThePotatoArchivist**
Updated gradle & all dependencies

Obviously you probably don't want to merge 1.20.1 changes into the 1.19 branch, this PR is just a formality.

According to your license, since the code has not changed in two years I am allowed to publish or redistribute it. Therefore, if no activity on this PR occurs, I will post a port version on my modrinth but I will make sure to credit you and link to the original mod.

Thanks!

### CODE REVIEW

**Comment by CammiePone** [comment]
actually i was thinking about porting it sometime soon anyways, since im setting up a server, so this is really big. thank you!

**Comment by ThePotatoArchivist** [comment]
Happy to help! Would you mind pinging back here when it's updated on modrinth?

**Comment by ThePotatoArchivist** [comment]
It seems that the 1.20 version will be released for Quilt only, would it be ok if I put my Fabric fork into a modpack I'm making and will put on Modrinth? I will credit you of course, and it will not make up a substantial part of the modpack.

**Comment by CammiePone** [comment]
no, but you can always run the pack on quilt since the majority of fabric mods run perfectly on quilt

**Comment by ThePotatoArchivist** [comment]
Understood, thank you!

**Pull request merged**
